### ISSUE TITLE
使用ILLA CLI 搭建 请求的api地址是localhost

### ISSUE THREAD

**Issue by rustdebug** [illa-family/illa-builder#335]
### Description

服务器搭建 地址应该是服务器的ip

### Steps to reproduce

服务器搭建 地址应该是服务器的ip
![image](https://user-images.githubusercontent.com/34772657/188775634-ad4ad0b6-2c33-4d98-b805-94c6d44626e5.png)

### ILLA Builder Version

1.6.4

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by smallSohoSolo** [comment]
Thanks for the feedback. We'll take a look.

**Comment by naj1n** [comment]
We have fixed this error in https://github.com/illa-family/illa/pull/28.
