### ISSUE TITLE
组件的位置计算bug

### ISSUE THREAD

**Issue by jeff-fe** [illa-family/illa-builder#336]
### Description

画布中的组件在预览模式和发布后展示的位置不一致

### Steps to reproduce

画布中的组件在预览模式和发布后展示的位置不一致

### ILLA Builder Version

1.6.4

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information
预览时
<img width="1502" alt="image" src="https://user-images.githubusercontent.com/19850462/188780856-7202a71a-a696-41ad-a066-fbf2e62815f8.png">
发布后
<img width="1479" alt="image" src="https://user-images.githubusercontent.com/19850462/188780942-fef381fe-52fc-4b2f-85bf-072b01f6e609.png">

**Comment by smallSohoSolo** [comment]
Thanks for the feedback. We'll take a look

**Comment by AruSeito** [comment]
This bug will be fixed in the next version.
The reason for this bug is that there is no synchronization when modifying on the canvas

**Comment by jeff-fe** [comment]
@AruSeito 想问下，后续有计划支持自定义组件吗？

**Comment by AruSeito** [comment]
The feature of custom component are already planned.We will support users to import published packages on the illa-builder.The premise is that the component is developed through the SDK we provide.
