### ISSUE TITLE
通过SSH私钥连接MySQL时需要密码可以不填

### ISSUE THREAD

**Issue by hiwjd** [illa-family/illa-builder#337]
### Description

通过SSH私钥连接MySQL时需要密码可以不填

### Steps to reproduce

1. 新建项目
2. 底部Action列表，点“新建”
3. 选择MySQL
4. 启用“通过SSH连接”
5. SSH凭证中密码留空，SSH密码留空
6. 点“创建资源”
7. SSH凭证中密码 提示“这是必填项”

![1122](https://user-images.githubusercontent.com/1838262/188783461-0aeb4a25-658c-42c1-b1fd-092e2d1303ef.png)

### ILLA Builder Version

1.0.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by smallSohoSolo** [comment]
Thanks for the feedback. We'll take a look.
