### ISSUE TITLE
交互可能存在问题

### ISSUE THREAD

**Issue by rustdebug** [illa-family/illa-builder#343]
### Description

当我测试数据库连接,无论成功还是失败都是跳转页面,导致看不到错误信息

### Steps to reproduce

![image](https://user-images.githubusercontent.com/34772657/189107628-89532f2f-d202-4090-84a5-8739464bec97.png)
docker 日志
![image](https://user-images.githubusercontent.com/34772657/189107736-af218b3f-70ed-4485-9fb4-0ec1fd3d588f.png)

### ILLA Builder Version

最新

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by naj1n** [comment]
It`s an internal server error in the docker logs. We have fixed it by pushing a new illa builder docker image. Maybe, u should deploy a new one after removing the old one.

**Comment by N0Noorz** [comment]
> It`s an internal server error in the docker logs. We have fixed it by pushing a new illa builder docker image. Maybe, u should deploy a new one after removing the old one.

有另外一个小问题，如果不输入端口号，点击测试连接会重定向到500页面，点击创建资源会提示输入端口号。

**Comment by naj1n** [comment]
It's a display error; we'll fix it as soon as possible.

**Comment by smallSohoSolo** [comment]
It is already fixed in v1.1.1.
