### ISSUE TITLE
创建Action报错

### ISSUE THREAD

**Issue by shaoqiangen** [illa-family/illa-builder#345]
### Description

create action error: ERROR: column \"template\" of relation \"actions\" does not exist (SQLSTATE 42703)

## 创建Action报错：
![image](https://user-images.githubusercontent.com/113163469/189286144-7a2968c7-72dd-4c65-8a87-f1adec67109e.png)

## 请求地址：
![image](https://user-images.githubusercontent.com/113163469/189286192-e1718c8a-7303-4e66-8cc3-676f272d2dee.png)

## 响应失败：
![image](https://user-images.githubusercontent.com/113163469/189286382-72e0d633-439f-4009-8b12-e8e766316f0b.png)

### ILLA Builder Version

1.0.1

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by naj1n** [comment]
We'll fix it by pushing a new illa builder docker image. You can deploy a new one after removing the old one.

**Comment by naj1n** [comment]
We have pushed the latest docker image. This error has been fixed.
