### ISSUE TITLE
Not sure how to get returned value from transformer

### ISSUE THREAD

**Issue by DeluxeOwl** [illa-family/illa-builder#367]
### Description

I'm trying to get the return value of a transformer in a text box.

### Steps to reproduce

1. Create a transformer that returns a string
2. Try to get the value in a text box
![image](https://user-images.githubusercontent.com/54327698/193413340-a40a4837-3cea-4ae2-be34-0237f9651533.png)
I'm really not sure how to get that string. OR any data for that matter.

### ILLA Builder Version

1.0.0

### Browser

Firefox

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

explained above.

**Comment by AruSeito** [comment]
This is bug.We'll fixed it in the near future

**Comment by smallSohoSolo** [comment]
This bug will be fixed in v1.1.1.
You can write under code to get the value
```js
transformer1.value
```
