### ISSUE TITLE
CODE_OF_CONDUCT.md has a small typo under the # Our Standards , # Examples of unacceptable behavior include: , # Point 4.

### ISSUE THREAD

**Issue by lavish-lekhari** [illa-family/illa-builder#390]
### Description

CODE_OF_CONDUCT.md has a small typo under the # Our Standards , # Examples of unacceptable behavior include: , # Point 4. 

### Steps to reproduce

Point 4 - Error - " Publishing others' "
Correction - " Publishing other's "

Please assign me this issue to solve with a hacktoberfest marked label to this issue so I can contribute to this and send a PR/MR for this which would be further counted in hacktoberfest-2022. 

Thank you so much :)

### ILLA Builder Version

1.0.0

### Browser

Google Chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by naj1n** [comment]
Sry, it's not a typo error.
