### ISSUE TITLE
numberInput have error when the value is 0 

### ISSUE THREAD

**Issue by LuXinZ** [illa-family/illa-builder#447]
### Description

if the value is 0 , you can not click the add button, i think 0 is false and cause this bug. 

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### ILLA Builder Version

1.2.3

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by cyx0928** [comment]
Hey There:

Thank you very for much the issue. We already merged your code. Much appreciated!
You can join our Discord Community for further communication!  Here is the Discord: https://discord.com/invite/illafamily.

Best,

ILLA Team
